plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}

// A dedicated signing key kept OUTSIDE this repo, at a stable path in the user's own
// profile (not any project or temp directory - both get wiped/regenerated by unrelated
// tooling on a dev machine, e.g. Android Studio/AVD Manager can recreate the *shared*
// ~/.android/debug.keystore that AGP falls back to by default). Every build signed with
// a different key forces Android to treat it as a different app: installing it can only
// replace the old one via a full uninstall, which wipes all alarms/settings instead of
// updating in place. Pinning one key here is what makes "install the new APK over the old
// one" behave like an actual update. If this file isn't present (e.g. building fresh on a
// different machine), the build quietly falls back to the platform's normal debug signing
// instead of failing - it just won't update cleanly over a build signed with this key.
val kuclabKeystore = file(System.getProperty("user.home") + "/.android/kuclab-clock.keystore")

android {
    namespace = "dev.kuclab.clock"
    compileSdk = 34

    defaultConfig {
        applicationId = "dev.kuclab.clock"
        minSdk = 26
        targetSdk = 34
        versionCode = 4
        versionName = "1.3"
    }

    signingConfigs {
        if (kuclabKeystore.exists()) {
            create("kuclab") {
                storeFile = kuclabKeystore
                storePassword = "KucLabClock-signing-2026"
                keyAlias = "kuclab"
                keyPassword = "KucLabClock-signing-2026"
            }
        }
    }

    buildTypes {
        debug {
            if (kuclabKeystore.exists()) {
                signingConfig = signingConfigs.getByName("kuclab")
            }
        }
        release {
            isMinifyEnabled = false
            if (kuclabKeystore.exists()) {
                signingConfig = signingConfigs.getByName("kuclab")
            }
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }

    composeOptions {
        kotlinCompilerExtensionVersion = "1.5.14"
    }
}

dependencies {
    val composeBom = platform("androidx.compose:compose-bom:2024.06.00")
    implementation(composeBom)
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.foundation:foundation")
    implementation("androidx.compose.material3:material3")
    implementation("androidx.activity:activity-compose:1.9.0")
    implementation("androidx.core:core-ktx:1.13.1")
}
